robot:
  type: so101_follower
  port: /dev/ttyACM1
  id: my_awesome_follower_arm
  cameras:
    side:
      type: opencv
      index_or_path: http://10.246.189.205:8080/video1
      width: 640
      height: 480
      fps: 30

teleop:
  type: so101_leader
  port: /dev/ttyACM0
  id: my_awesome_leader_arm

dataset:
  repo_id: chiqvo/so101_test
  root: /home/wadith/datasets/so101_test
  num_episodes: 10
  episode_time_s: 20
  reset_time_s: 5
  push_to_hub: true
  single_task: "Pick and place"

