robot:
  type: so101_follower
  port: /dev/ttyACM1
  id: my_awesome_follower_arm
  cameras:
    side:
      type: opencv
      index_or_path: "http://10.246.188.197:8080/video0"
      width: 640
      height: 360
      fps: 25
    wrist:
      type: opencv
      index_or_path: "http://10.246.188.197:8080/video1"
      width: 640
      height: 360
      fps: 25

teleop:
  type: so101_leader
  port: /dev/ttyACM0
  id: my_awesome_leader_arm

dataset:
  repo_id: chiqvo/so101_test
  root: /home/wadith/datasets/so101_test
  num_episodes: 1
  episode_time_s: 20
  reset_time_s: 5
  push_to_hub: false
  single_task: "Pick and place"
  streaming_encoding: true

